### ISSUE TITLE
Compatibility with 2.1.0

### ISSUE THREAD

**Issue by manuraj17** [eugenpt/lite-xl-vibe#25]
Was trying this with `2.1.0` and it seems to be not supported yet. I would like to use it with the latest version as I want to try out some `lsp` stuff. 

- Can someone help me identify where this check happens? I will make the changes and try it out locally in case it's not planned anytime soon for the plugin.

TIA.

**Comment by manuraj17** [comment]
Sorry, found it [here](https://lite-xl.com/en/tutorials/simple-plugin)

**Comment by eugenpt** [comment]
Sorry, I've lost touch with this project and don't keep up with lite-xl progress =(

If only I got a job as a lua dev ;)..

**Comment by mandarvaze** [comment]
@manuraj17 Were you able to make this plugin work with 2.1.0 ?
The link you pointed to is tutorial for writing a plugin for lite-xl and I couldn't figure out how to change this plugin to make it work with 2.1.0

@eugenpt can you point to where one can update the version so that it works with 2.1.0 ? ( I get that there may be more that updating the number, but that could be a start)

**Comment by mandarvaze** [comment]
@eugenpt  I can help test when you are done with your inprogress items
looking forward.
